! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


MODULE C_MODIFIED_SHEPARD
USE ISO_FORTRAN_ENV , ONLY : REAL64
  IMPLICIT NONE


CONTAINS


  
  SUBROUTINE C_SHEPMOD(M, N, X_DIM_1, X_DIM_2, X, RW_DIM_1, RW, IER) BIND(C)
    USE MODIFIED_SHEPARD, ONLY: SHEPMOD
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: X_DIM_1
    INTEGER, INTENT(IN) :: X_DIM_2
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(X_DIM_1,X_DIM_2) :: X
    INTEGER, INTENT(IN) :: RW_DIM_1
    REAL(KIND=REAL64), INTENT(OUT), DIMENSION(RW_DIM_1) :: RW
    INTEGER, INTENT(OUT) :: IER
  
    CALL SHEPMOD(M, N, X, RW, IER)
  END SUBROUTINE C_SHEPMOD
  

  
  SUBROUTINE C_SHEPMODVAL(XP_DIM_1, XP, M, N, X_DIM_1, X_DIM_2, X, RW_DIM_1, RW, WTS_DIM_1, WTS, IER) BIND(C)
    USE MODIFIED_SHEPARD, ONLY: SHEPMODVAL
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: XP_DIM_1
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(XP_DIM_1) :: XP
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: X_DIM_1
    INTEGER, INTENT(IN) :: X_DIM_2
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(X_DIM_1,X_DIM_2) :: X
    INTEGER, INTENT(IN) :: RW_DIM_1
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(RW_DIM_1) :: RW
    INTEGER, INTENT(IN) :: WTS_DIM_1
    REAL(KIND=REAL64), INTENT(OUT), DIMENSION(WTS_DIM_1) :: WTS
    INTEGER, INTENT(OUT) :: IER
  
    CALL SHEPMODVAL(XP, M, N, X, RW, WTS, IER)
  END SUBROUTINE C_SHEPMODVAL
  
END MODULE C_MODIFIED_SHEPARD

