
PROGRAM SIZE_TEST
  USE REAL_PRECISION
  USE VTDELAUNAY
  IMPLICIT NONE
  
    INTEGER :: D
    REAL(KIND=R8) :: PTS
    REAL(KIND=R8) :: P
    REAL(KIND=R8) :: WORK
    INTEGER :: SIMP
    REAL(KIND=R8) :: WEIGHTS
    INTEGER :: ERR
    REAL(KIND=R8) :: INTERP_IN_OPT
    REAL(KIND=R8) :: INTERP_OUT_OPT
    REAL(KIND=R8) :: EPS_OPT
    REAL(KIND=R8) :: RNORM_OPT
    INTEGER :: BUDGET_OPT
    REAL(KIND=R8) :: EXTRAP_OPT
  
    PRINT *, 'D', SIZEOF(D)
    PRINT *, 'PTS', SIZEOF(PTS)
    PRINT *, 'P', SIZEOF(P)
    PRINT *, 'WORK', SIZEOF(WORK)
    PRINT *, 'SIMP', SIZEOF(SIMP)
    PRINT *, 'WEIGHTS', SIZEOF(WEIGHTS)
    PRINT *, 'ERR', SIZEOF(ERR)
    PRINT *, 'INTERP_IN_OPT', SIZEOF(INTERP_IN_OPT)
    PRINT *, 'INTERP_OUT_OPT', SIZEOF(INTERP_OUT_OPT)
    PRINT *, 'EPS_OPT', SIZEOF(EPS_OPT)
    PRINT *, 'RNORM_OPT', SIZEOF(RNORM_OPT)
    PRINT *, 'BUDGET_OPT', SIZEOF(BUDGET_OPT)
    PRINT *, 'EXTRAP_OPT', SIZEOF(EXTRAP_OPT)
END PROGRAM SIZE_TEST

