!     Module generated by fmodpy for fortran file named 'VTDELAUNAY'     
!=====================================================================
MODULE VTDELAUNAY_WRAPPER
  ! Any necessary "USE" statements
  USE REAL_PRECISION
  USE VTDELAUNAY
  ! Make sure it is clear that no implicit types are used in this wrapper
  IMPLICIT NONE
  ! Any interfaces defined for "PROCEDURE" declarations
  
CONTAINS
  !     Fortran wrapper for DELAUNAYP, callable from C     
  !========================================================

  SUBROUTINE c_DELAUNAYP( D, PTS_0, PTS_1, PTS, P_0, P_1, P, WORK_0, W&
     &ORK, SIMP_0, SIMP_1, SIMP, WEIGHTS_0, WEIGHTS_1, WEIGHTS, ERR_0,&
     & ERR, INTERP_IN_OPT_0, INTERP_IN_OPT_1, INTERP_IN_OPT, INTERP_IN&
     &_OPT_PRESENT, INTERP_OUT_OPT_0, INTERP_OUT_OPT_1, INTERP_OUT_OPT&
     &, INTERP_OUT_OPT_PRESENT, EPS_OPT, EPS_OPT_PRESENT, RNORM_OPT_0,&
     & RNORM_OPT, RNORM_OPT_PRESENT, BUDGET_OPT, BUDGET_OPT_PRESENT, E&
     &XTRAP_OPT, EXTRAP_OPT_PRESENT ) BIND(c)
    ! This subroutine's only purpose is to call the source fortran
    !  code while also being accessible from C.
    INTEGER, INTENT(IN) :: D
    INTEGER, INTENT(IN) :: PTS_0
    INTEGER, INTENT(IN) :: PTS_1
    REAL(KIND=R8), DIMENSION(PTS_0,PTS_1), INTENT(IN) :: PTS
    INTEGER, INTENT(IN) :: P_0
    INTEGER, INTENT(IN) :: P_1
    REAL(KIND=R8), DIMENSION(P_0,P_1), INTENT(IN) :: P
    INTEGER, INTENT(IN) :: WORK_0
    REAL(KIND=R8), DIMENSION(WORK_0), INTENT(INOUT) :: WORK
    INTEGER, INTENT(IN) :: SIMP_0
    INTEGER, INTENT(IN) :: SIMP_1
    INTEGER, DIMENSION(SIMP_0,SIMP_1), INTENT(OUT) :: SIMP
    INTEGER, INTENT(IN) :: WEIGHTS_0
    INTEGER, INTENT(IN) :: WEIGHTS_1
    REAL(KIND=R8), DIMENSION(WEIGHTS_0,WEIGHTS_1), INTENT(OUT) :: WEIG&
         &HTS
    INTEGER, INTENT(IN) :: ERR_0
    INTEGER, DIMENSION(ERR_0), INTENT(OUT) :: ERR
    LOGICAL, INTENT(IN) :: INTERP_IN_OPT_PRESENT
    INTEGER, INTENT(IN) :: INTERP_IN_OPT_0
    INTEGER, INTENT(IN) :: INTERP_IN_OPT_1
    REAL(KIND=R8), DIMENSION(INTERP_IN_OPT_0,INTERP_IN_OPT_1), INTENT(&
         &IN), OPTIONAL :: INTERP_IN_OPT
    LOGICAL, INTENT(IN) :: INTERP_OUT_OPT_PRESENT
    INTEGER, INTENT(IN) :: INTERP_OUT_OPT_0
    INTEGER, INTENT(IN) :: INTERP_OUT_OPT_1
    REAL(KIND=R8), DIMENSION(INTERP_OUT_OPT_0,INTERP_OUT_OPT_1), INTEN&
         &T(OUT), OPTIONAL :: INTERP_OUT_OPT
    LOGICAL, INTENT(IN) :: EPS_OPT_PRESENT
    REAL(KIND=R8), INTENT(IN), OPTIONAL :: EPS_OPT
    LOGICAL, INTENT(IN) :: RNORM_OPT_PRESENT
    INTEGER, INTENT(IN) :: RNORM_OPT_0
    REAL(KIND=R8), DIMENSION(RNORM_OPT_0), INTENT(OUT), OPTIONAL :: RN&
         &ORM_OPT
    LOGICAL, INTENT(IN) :: BUDGET_OPT_PRESENT
    INTEGER, INTENT(IN), OPTIONAL :: BUDGET_OPT
    LOGICAL, INTENT(IN) :: EXTRAP_OPT_PRESENT
    REAL(KIND=R8), INTENT(IN), OPTIONAL :: EXTRAP_OPT
    ! Preparation code before function call (copying character arrays)
    
    ! Calling source fortran function
    IF (INTERP_IN_OPT_PRESENT) THEN
       IF (INTERP_OUT_OPT_PRESENT) THEN
          IF (EPS_OPT_PRESENT) THEN
             IF (RNORM_OPT_PRESENT) THEN
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, EPS_OPT=EPS_OPT, RNO&
                           &RM_OPT=RNORM_OPT, BUDGET_OPT=BUDGET_OPT, E&
                           &XTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, EPS_OPT=EPS_OPT, RNO&
                           &RM_OPT=RNORM_OPT, BUDGET_OPT=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, EPS_OPT=EPS_OPT, RNO&
                           &RM_OPT=RNORM_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, EPS_OPT=EPS_OPT, RNO&
                           &RM_OPT=RNORM_OPT)
                   ENDIF
                ENDIF
             ELSE
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, EPS_OPT=EPS_OPT, BUD&
                           &GET_OPT=BUDGET_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, EPS_OPT=EPS_OPT, BUD&
                           &GET_OPT=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, EPS_OPT=EPS_OPT, EXT&
                           &RAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, EPS_OPT=EPS_OPT)
                   ENDIF
                ENDIF
             ENDIF
          ELSE
             IF (RNORM_OPT_PRESENT) THEN
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, RNORM_OPT=RNORM_OPT,&
                           & BUDGET_OPT=BUDGET_OPT, EXTRAP_OPT=EXTRAP_&
                           &OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, RNORM_OPT=RNORM_OPT,&
                           & BUDGET_OPT=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, RNORM_OPT=RNORM_OPT,&
                           & EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, RNORM_OPT=RNORM_OPT)
                   ENDIF
                ENDIF
             ELSE
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, BUDGET_OPT=BUDGET_OP&
                           &T, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, BUDGET_OPT=BUDGET_OP&
                           &T)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT, EXTRAP_OPT=EXTRAP_OP&
                           &T)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, INTERP_OU&
                           &T_OPT=INTERP_OUT_OPT)
                   ENDIF
                ENDIF
             ENDIF
          ENDIF
       ELSE
          IF (EPS_OPT_PRESENT) THEN
             IF (RNORM_OPT_PRESENT) THEN
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, EPS_OPT=E&
                           &PS_OPT, RNORM_OPT=RNORM_OPT, BUDGET_OPT=BU&
                           &DGET_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, EPS_OPT=E&
                           &PS_OPT, RNORM_OPT=RNORM_OPT, BUDGET_OPT=BU&
                           &DGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, EPS_OPT=E&
                           &PS_OPT, RNORM_OPT=RNORM_OPT, EXTRAP_OPT=EX&
                           &TRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, EPS_OPT=E&
                           &PS_OPT, RNORM_OPT=RNORM_OPT)
                   ENDIF
                ENDIF
             ELSE
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, EPS_OPT=E&
                           &PS_OPT, BUDGET_OPT=BUDGET_OPT, EXTRAP_OPT=&
                           &EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, EPS_OPT=E&
                           &PS_OPT, BUDGET_OPT=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, EPS_OPT=E&
                           &PS_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, EPS_OPT=E&
                           &PS_OPT)
                   ENDIF
                ENDIF
             ENDIF
          ELSE
             IF (RNORM_OPT_PRESENT) THEN
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, RNORM_OPT&
                           &=RNORM_OPT, BUDGET_OPT=BUDGET_OPT, EXTRAP_&
                           &OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, RNORM_OPT&
                           &=RNORM_OPT, BUDGET_OPT=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, RNORM_OPT&
                           &=RNORM_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, RNORM_OPT&
                           &=RNORM_OPT)
                   ENDIF
                ENDIF
             ELSE
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, BUDGET_OP&
                           &T=BUDGET_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, BUDGET_OP&
                           &T=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT, EXTRAP_OP&
                           &T=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_IN_OPT=INTERP_IN_OPT)
                   ENDIF
                ENDIF
             ENDIF
          ENDIF
       ENDIF
    ELSE
       IF (INTERP_OUT_OPT_PRESENT) THEN
          IF (EPS_OPT_PRESENT) THEN
             IF (RNORM_OPT_PRESENT) THEN
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, EPS_OPT&
                           &=EPS_OPT, RNORM_OPT=RNORM_OPT, BUDGET_OPT=&
                           &BUDGET_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, EPS_OPT&
                           &=EPS_OPT, RNORM_OPT=RNORM_OPT, BUDGET_OPT=&
                           &BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, EPS_OPT&
                           &=EPS_OPT, RNORM_OPT=RNORM_OPT, EXTRAP_OPT=&
                           &EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, EPS_OPT&
                           &=EPS_OPT, RNORM_OPT=RNORM_OPT)
                   ENDIF
                ENDIF
             ELSE
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, EPS_OPT&
                           &=EPS_OPT, BUDGET_OPT=BUDGET_OPT, EXTRAP_OP&
                           &T=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, EPS_OPT&
                           &=EPS_OPT, BUDGET_OPT=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, EPS_OPT&
                           &=EPS_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, EPS_OPT&
                           &=EPS_OPT)
                   ENDIF
                ENDIF
             ENDIF
          ELSE
             IF (RNORM_OPT_PRESENT) THEN
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, RNORM_O&
                           &PT=RNORM_OPT, BUDGET_OPT=BUDGET_OPT, EXTRA&
                           &P_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, RNORM_O&
                           &PT=RNORM_OPT, BUDGET_OPT=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, RNORM_O&
                           &PT=RNORM_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, RNORM_O&
                           &PT=RNORM_OPT)
                   ENDIF
                ENDIF
             ELSE
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, BUDGET_&
                           &OPT=BUDGET_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, BUDGET_&
                           &OPT=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT, EXTRAP_&
                           &OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, INTERP_OUT_OPT=INTERP_OUT_OPT)
                   ENDIF
                ENDIF
             ENDIF
          ENDIF
       ELSE
          IF (EPS_OPT_PRESENT) THEN
             IF (RNORM_OPT_PRESENT) THEN
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, EPS_OPT=EPS_OPT, RNORM_OPT=RNORM_OPT, &
                           &BUDGET_OPT=BUDGET_OPT, EXTRAP_OPT=EXTRAP_O&
                           &PT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, EPS_OPT=EPS_OPT, RNORM_OPT=RNORM_OPT, &
                           &BUDGET_OPT=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, EPS_OPT=EPS_OPT, RNORM_OPT=RNORM_OPT, &
                           &EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, EPS_OPT=EPS_OPT, RNORM_OPT=RNORM_OPT)
                   ENDIF
                ENDIF
             ELSE
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, EPS_OPT=EPS_OPT, BUDGET_OPT=BUDGET_OPT&
                           &, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, EPS_OPT=EPS_OPT, BUDGET_OPT=BUDGET_OPT&
                           &)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, EPS_OPT=EPS_OPT, EXTRAP_OPT=EXTRAP_OPT&
                           &)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, EPS_OPT=EPS_OPT)
                   ENDIF
                ENDIF
             ENDIF
          ELSE
             IF (RNORM_OPT_PRESENT) THEN
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, RNORM_OPT=RNORM_OPT, BUDGET_OPT=BUDGET&
                           &_OPT, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, RNORM_OPT=RNORM_OPT, BUDGET_OPT=BUDGET&
                           &_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, RNORM_OPT=RNORM_OPT, EXTRAP_OPT=EXTRAP&
                           &_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, RNORM_OPT=RNORM_OPT)
                   ENDIF
                ENDIF
             ELSE
                IF (BUDGET_OPT_PRESENT) THEN
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, BUDGET_OPT=BUDGET_OPT, EXTRAP_OPT=EXTR&
                           &AP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, BUDGET_OPT=BUDGET_OPT)
                   ENDIF
                ELSE
                   IF (EXTRAP_OPT_PRESENT) THEN
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR, EXTRAP_OPT=EXTRAP_OPT)
                   ELSE
                      CALL DELAUNAYP(D, PTS, P, WORK, SIMP, WEIGHTS, E&
                           &RR)
                   ENDIF
                ENDIF
             ENDIF
          ENDIF
       ENDIF
    ENDIF
    ! Copying out any necessary values for return (character arrays)
    
  END SUBROUTINE c_DELAUNAYP

END MODULE VTDELAUNAY_WRAPPER
