
PROGRAM SIZE_TEST
  USE ISO_FORTRAN_ENV
  USE BOOTSTRAPPED_BOX_SPLINES
  IMPLICIT NONE
  
    REAL(KIND=REAL64) :: A
    INTEGER :: IDX
  
    PRINT *, 'A', SIZEOF(A)
    PRINT *, 'IDX', SIZEOF(IDX)
END PROGRAM SIZE_TEST

